// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your web API key',
    appId: '1:243574472060:web:457ac10e54678027a578f9',
    messagingSenderId: '243574472060',
    projectId: 'todolist-3b156',
    authDomain: 'todolist-3b156.firebaseapp.com',
    storageBucket: 'todolist-3b156.firebasestorage.app',
    measurementId: 'G-KDSP13LFBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your android API key',
    appId: '1:243574472060:android:17faf95a3ca29ee2a578f9',
    messagingSenderId: '243574472060',
    projectId: 'todolist-3b156',
    storageBucket: 'todolist-3b156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your ios API key',
    appId: '1:243574472060:ios:f31b479ef63c484ca578f9',
    messagingSenderId: '243574472060',
    projectId: 'todolist-3b156',
    storageBucket: 'todolist-3b156.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your macos API key',
    appId: '1:243574472060:ios:f31b479ef63c484ca578f9',
    messagingSenderId: '243574472060',
    projectId: 'todolist-3b156',
    storageBucket: 'todolist-3b156.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Your Windows API key',
    appId: '1:243574472060:web:fbdd25d0b2158120a578f9',
    messagingSenderId: '243574472060',
    projectId: 'todolist-3b156',
    authDomain: 'todolist-3b156.firebaseapp.com',
    storageBucket: 'todolist-3b156.firebasestorage.app',
    measurementId: 'G-MHKGGNJMV3',
  );
}
